Title.find_or_create_by(name: "Vogue")
Title.find_or_create_by(name: "W")
Title.find_or_create_by(name: "Glamour")
Title.find_or_create_by(name:"Vanity Fair")
Title.find_or_create_by(name: "Washington Post")
Title.find_or_create_by(name: "Golf Digest")
Title.find_or_create_by(name: "The New York Times")
Title.find_or_create_by(name: "Wired")
Title.find_or_create_by(name: "Bon Appetit")
Title.find_or_create_by(name: "Elle")
