Title.create!(name: "Vogue")
Title.create!(name: "W")
Title.create!(name: "Glamour")
Title.create!(name:"Vanity Fair")
Title.create!(name: "Washington Post")
Title.create!(name: "Golf Digest")
Title.create!(name: "The New York Times")
Title.create!(name: "Wired")
Title.create!(name: "Bon Appetit")
Title.create!(name: "Elle")
